spring:
  application:
    name: springboot-auth
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_auth
    username: root
    password: kishor@2233#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  servlet:
    context-path: /api/v1.0